# Generated by Django 5.2.16 on 2026-07-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100, help_text='Maximum possible score for this assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Closed', 'Closed')], default='Published', max_length=20),
        ),
    ]
