# Generated by Django 5.2.16 on 2026-07-15 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_submission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student', 'attempt_number')},
        ),
    ]
