# Generated by Django 5.2.9 on 2025-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staff_designation_staff_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_exam_officer',
            field=models.BooleanField(default=False),
        ),
    ]
