# Generated by Django 5.2.16 on 2026-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizationsettings_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='min_password_length',
            field=models.IntegerField(default=8),
        ),
    ]
