# Generated by Django 5.2.16 on 2026-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examattempt_examanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='file_answer',
            field=models.FileField(blank=True, null=True, upload_to='exams/answers/files/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TEXT', 'Short/Long Text'), ('FILE', 'File Upload')], default='MCQ', max_length=10),
        ),
    ]
