# Generated by Django 5.2.9 on 2025-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teachers_alter_course_teacher'),
        ('users', '0006_staff_designation_staff_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.student'),
        ),
    ]
