# Generated by Django 5.2.16 on 2026-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollmentrequest_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='upload_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
